export const API_ROUTES = {
    LOGINADMIN: 'admin/login',
    LOGINUSER: 'residential/login',
    FORGOTPASSWORD: 'auth/forgot-password',
    VERIFYOTP: 'auth/verify-forgot-otp',
    RESETPASSWORD: 'auth/reset-password',
    ADD_MEMBERS: 'admin/residential',
    UPDATE_MEMBER: (id) => `admin/residential/${id}`,
    DELETE_MEMBER: (id) => `admin/residential/terminate-account/${id}`,
    UPLOAD_PAYMENT: 'payment/upload',
    PAYMENT_HISTORY: '/payment/history',
    RESIDENTIAL_PAYMENTS: 'admin/residential/payments',
    VERIFY_PAYMENT: (id) => `/payment/admin/${id}/verify`,
    PROFILE_GET: 'residential/profile',
    MY_NOTIFICATION: 'notifications',
    ADMIN_PROFILE: 'admin/profile',
    ADMIN_NOTIFICATION: 'events/notification/admin',
    GETALL_ANNOUNCEMENT: 'events/admin',
    ADD_EVENT: 'events/admin',
    UPDATE_EVENT: (id) => `events/admin/${id}`,
    GET_ALL_RESIDENTAILS: 'admin/residential',
    // GET_RESIDENTAIL : (id) =>`admin/residential/${id}` ,
    DELETE_EVENT: (id) => `events/admin/${id}`,
    MEMBERLIST: 'admin/residential/member-listing',
    MEMEBERLIST_APPROVE: (id) => `admin/residential/verify-member/${id}`,
    SOCIETYGET: 'society',
    UPDATESOCIETY: (id) => `society/${id}`,
    CONTACT_US: 'admin/post-contact',
    USERCONTACT_US: 'contact-us',

    UPDATE_USER_PROFILE: `residential/profile`,
    TERMINATION_REQUEST: `residential/termination`,
    GET_TERMINATION_REQUESTS: `admin/residential/termination-requests`


}