export const API_ROUTES = {
    LOGINADMIN: 'admin/login',
    LOGINUSER: 'residential/login',
    ADD_MEMBERS: 'admin/residential',
    UPLOAD_PAYMENT: 'payment/upload',
    PAYMENT_HISTORY: '/payment/history',
    RESIDENTIAL_PAYMENTS: 'admin/residential/payments',
    VERIFY_PAYMENT: (id) => `/payment/admin/${id}/verify`,
    PROFILE_GET: 'residential/profile',
    MY_NOTIFICATION: 'notifications',
    ADMIN_PROFILE: 'admin/profile',
    ADMIN_NOTIFICATION: 'events/notification/admin',
    GETALL_ANNOUNCEMENT: 'events/admin',
    ADD_EVENT: 'events/admin',
    UPDATE_EVENT: (id) => `events/admin/${id}`,
    GET_ALL_RESIDENTAILS: 'admin/residential',
    DELETE_EVENT: (id) => `events/admin/${id}`,
    MEMBERLIST: 'admin/residential/member-listing',
    MEMEBERLIST_APPROVE: (id) => `admin/residential/verify-member/${id}`,
    SOCIETYGET:'society',
    UPDATESOCIETY:(id) => `society/${id}`,
    CONTACT_US:'admin/post-contact',
    USERCONTACT_US:'contact-us'
}